services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.136.0
    container_name: otel-collector
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    restart: unless-stopped
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/otel-collector-config.yaml:ro
    environment:
      - OTEL_LOG_LEVEL=info
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:13133/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
