[project]
name = "agent-framework-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-framework>=1.0.0b251016",
]

[dependency-groups]
dev = [
    "ruff>=0.13.3",
]

[tool.uv]
prerelease = "allow"
