[project]
name = "agent-framework-quickstart-with-ollama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agent-framework>=1.0.0b251001",
]

[tool.uv]
prerelease = "allow"
